### ISSUE TITLE
No activations detected

### ISSUE THREAD

**Issue by yangbincv** [WalterSimoncini/fungivision#1]
Thank you very much for open-sourcing the code, while reproducing it, I encountered the error: No activations detected, run forward after add_hooks(model). Where should add_hooks(model) be added to the code?

**Comment by WalterSimoncini** [comment]
You're welcome! That's strange, could you share the code snippet that caused the error? `add_hooks(model)` is done automatically by the wrapper [here](https://github.com/WalterSimoncini/fungivision/blob/646aea416f0e03b874be3b25aa0e73da4e387b75/src/fungivision/wrapper.py#L61). Does this happen with any model? Or only with a specific one?

If you were to compute FUNGI features without using this library, you would use `add_hooks` (and related calls) as in [this script](https://github.com/WalterSimoncini/no-train-all-gain/blob/66c393d89e5e62f6e9e53afe5c1a91f92f4e5e4f/grads_kl.py#L134).

**Comment by yangbincv** [comment]
Thank you for your reply, the problem has been solved. The cause was a mismatch of torch versions.
